var recipesData = [
    { title:'Chiffon Cake', path:'./img/recipes/recipes-02-md.jpg', shortDesc:'Jujubes danish cake cake apple pie croissant bonbon.',desc:'Lemon drops lollipop pie marzipan tootsie roll bonbon marshmallow candy gummies. Dragée tart cake bear claw. Cheesecake gingerbread pie macaroon. Oat cake chupa chups toffee donut sugar plum liquorice.'},
    { title:'Chocolate Mousse', path:'./img/recipes/recipes-03-md.jpg', shortDesc:'Sesame snaps tiramisu topping soufflé chocolate',desc:'Sweet cake chocolate tart gummies. Topping gummi bears dessert chocolate. Gingerbread oat cake cake apple pie cotton candy dessert. Candy canes liquorice sesame snaps pastry caramels candy canes oat cake.'},
    { title:'Chocolate Chip Cookies', path:'./img/recipes/recipes-04-md.jpg', shortDesc:'Chocolate bar lollipop icing.',desc:'Cake brownie topping. Marzipan liquorice caramels. Marshmallow toffee halvah jujubes powder.'},
    { title:'Carrot Cake', path:'./img/recipes/recipes-05-md.jpg', shortDesc:'Pie wafer cupcake bonbon donut lemon drops jelly lemon drops',desc:'Sweet cake chocolate tart gummies. Topping gummi bears dessert chocolate. Gingerbread oat cake cake apple pie cotton candy dessert. Candy canes liquorice sesame snaps pastry caramels candy canes oat cake.'},
    { title:'Chocolate Oatmeal Cookies', path:'./img/recipes/recipes-06-md.jpg', shortDesc:'Jujubes danish cake cake apple pie croissant bonbon.',desc:'Macaroon gummi bears cookie marshmallow bear claw caramels sweet cotton candy. Muffin gingerbread chocolate cake cupcake muffin topping cookie donut. Carrot cake wafer icing cupcake.'},
    { title:'Chocolate Fudge', path:'./img/recipes/recipes-07-md.jpg',shortDesc:'Muffin apple pie oat cake lollipop topping', desc:'Lorem ipsum dolor sit amet'},
    { title:'Strawberry Short Cake', path:'./img/recipes/recipes-08-md.jpg', shortDesc:'Chocolate bar lollipop icing.',desc:'Pellentesque interdum lacus eget ligula tempus'},
    { title:'Red Velvet Cake', path:'./img/recipes/recipes-09-md.jpg', shortDesc:'Jujubes danish cake cake apple pie croissant bonbon.',desc:'Marzipan sweet roll cheesecake icing cheesecake marshmallow tiramisu sugar plum. Carrot cake toffee carrot cake candy canes bear claw. Sweet candy canes topping pastry bonbon apple pie.'},
    { title:'Coffee Macarons', path:'./img/recipes/recipes-10-md.jpg', shortDesc:'Chocolate bar lollipop icing.',desc:'Bonbon halvah powder bear claw bear claw tootsie roll. Jujubes halvah donut bonbon macaroon sweet marzipan pie sesame snaps. Sugar plum bear claw candy canes chupa chups marshmallow sesame snaps halvah chocolate apple pie.'},

];
